myicecast:
   image: alastairhm/docker-icecast
   volumes:
      - /home/alastair/Music/:/opt/music
   ports:
      - "8000:8000"
      - "6600:6600"
frontend:
   build : alastairhm/mpd-webclient
   links:
      - myicecast:icy 
   ports:
      - "80:80"
